sudo: required

language: ruby

services:
  - docker

script:
  - bundle exec rspec

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jadametz/serverspec;
    fi
